version: "3.5"
services:
  beacon-chain:
    build:
      context: ./beacon-chain
      args:
        BEACON_API_PORT: 3500
        UPSTREAM_VERSION: 22.4.0
    environment:
      BEACON_API_PORT: 3500
      HTTP_WEB3PROVIDER: "http://goerli-geth.dappnode:8545"
      CHECKPOINT_SYNC_URL: ""
      EXTRA_OPTS: ""
    volumes:
      - "teku-prater-data:/opt/teku/data"
    ports:
      - 9000/tcp
      - 9000/udp
    restart: unless-stopped
    image: "beacon-chain.teku-prater.dnp.dappnode.eth:0.1.0"
  validator:
    build:
      context: ./validator
      args:
        UPSTREAM_VERSION: 22.4.0
    environment:
      BEACON_NODE_ADDR: "http://beacon-chain.teku-prater.dappnode:3500"
      HTTP_WEB3SIGNER: "http://web3signer.web3signer-prater.dappnode:9000"
      PUBLIC_KEYS_FILE: /public_keys.txt
      GRAFFITI: validating_from_DAppNode
      SUPERVISOR_CONF: /etc/supervisor/conf.d/supervisord.conf
      INITIAL_STATE: ""
      EXTRA_OPTS: ""
    restart: unless-stopped
    image: "validator.teku-prater.dnp.dappnode.eth:0.1.0"
volumes:
  teku-prater-data: {}
