version: "3.5"
services:
  teku:
    build:
      context: ./build
      args:
        BEACON_API_PORT: 3500"
        UPSTREAM_VERSION: 22.1.1
    user: root
    image: "teku.teku-prater.dnp.dappnode.eth:0.1.0"
    volumes:
      - "teku-prater-data:/opt/teku/data"
      - "teku-public-keys:/opt/teku/public-keys"
    environment:
      BEACON_API_PORT: "3500"
      HTTP_WEB3PROVIDER: "http://goerli-geth.dappnode:8545"
      HTTP_WEB3SIGNER: "http://web3signer.web3signer-prater.dappnode:9000"
      PUBLIC_KEYS_FILE: /opt/teku/public-keys/public_keys.txt
      INITIAL_STATE: ""
      EXTRA_OPTS: ""
    ports:
      - "9000/tcp"
      - "9000/udp"
    restart: unless-stopped
volumes:
  teku-prater-data: {}
  teku-public-keys: {}
